version: "3.7"

services:
  postgres-dev:
    image: postgres:13-alpine
    container_name: postgres
    ports:
      - 54320:5432
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data: {}
